//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::file::Entity as File;
pub use super::user::Entity as User;
pub use super::workspace::Entity as Workspace;
pub use super::setting::Entity as Setting;
pub use super::ai_source::Entity as AiSource;
pub use super::ai_model::Entity as AiModel;