//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, Eq)]
#[sea_orm(table_name = "user")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub nickname: String,
    pub avatar: Option<Vec<u8>>,
    pub password: String,
    pub mail: Option<String>,
    pub r#type: String,
    pub ref_user_id: Option<String>,
    pub create_time: i64,
    pub update_time: i64,
    pub state: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Eq, FromQueryResult)]
#[serde(rename_all = "camelCase")]
pub struct DataTransModel {
    pub id: String,
    pub username: String,
    pub nickname: String,
    pub avatar: Option<Vec<u8>>,
    pub mail: Option<String>,
    pub r#type: String,
    pub ref_user_id: Option<String>,
    pub ref_user_name: Option<String>,
    pub create_time: i64,
    pub update_time: i64,
    pub state: i8,
}
